import type { Metadata } from "next";
import Link from "next/link";
import { CARD, Logo, PageGlow } from "@/app/components/ui";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How Oviflow collects, uses, and protects your data.",
};

const LAST_UPDATED = "7 August 2026";

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-white text-neutral-900 relative overflow-hidden">
      <PageGlow />

      <div className="relative mx-auto max-w-3xl px-6 py-10 sm:py-14">
        <div className="flex items-center gap-2 mb-8">
          <Logo />
        </div>

        <div className={CARD}>
          <h1 className="text-3xl font-semibold tracking-tight mb-2">Privacy Policy</h1>
          <p className="text-sm text-neutral-400 mb-8">Last updated: {LAST_UPDATED}</p>

          <div className="space-y-6 text-sm leading-relaxed text-neutral-700">
            <Section title="1. Who we are">
              <p>
                Oviflow (&quot;Oviflow&quot;, &quot;we&quot;, &quot;us&quot;) provides an AI phone
                receptionist service for small businesses in Australia. This policy explains what
                personal information we collect, why, and how it&apos;s handled — both for
                business owners who sign up for Oviflow, and for the customers who call an
                Oviflow-powered phone number.
              </p>
            </Section>

            <Section title="2. Information we collect">
              <p className="mb-2">
                <strong>From business owners (account holders):</strong> name, email address,
                phone number, business details you provide during setup (services, hours,
                pricing, FAQs, and any industry-specific information), payment details (processed
                by Stripe — we don&apos;t store card numbers ourselves), and any files you upload
                (e.g. menu photos).
              </p>
              <p>
                <strong>From callers (your customers):</strong> when someone calls an
                Oviflow-powered number, we may collect their phone number, a recording and
                transcript of the call, and a summary generated by our AI (including any details
                they choose to share, such as their name or what they&apos;re calling about).
              </p>
            </Section>

            <Section title="3. How we use your information">
              <ul className="list-disc pl-5 space-y-1.5">
                <li>To operate the AI receptionist — answering calls, understanding requests, and booking appointments where enabled.</li>
                <li>To send you (the business owner) call summaries and notifications by email and/or SMS.</li>
                <li>To send callers a confirmation text, but only if they gave verbal consent during the call.</li>
                <li>To process payments and manage your subscription.</li>
                <li>To improve the reliability and accuracy of the service.</li>
                <li>To comply with legal obligations, including Australian telecommunications and privacy law.</li>
              </ul>
            </Section>

            <Section title="4. Third-party services we use">
              <p className="mb-2">
                Oviflow is built on top of several third-party providers, each of which processes
                data on our behalf under their own security and privacy terms:
              </p>
              <ul className="list-disc pl-5 space-y-1.5">
                <li><strong>Vapi</strong> — voice AI platform that answers calls, and stores call recordings/transcripts.</li>
                <li><strong>Anthropic (Claude)</strong> — powers the AI&apos;s understanding and responses.</li>
                <li><strong>Twilio</strong> — phone numbers, call routing, and SMS delivery.</li>
                <li><strong>Google</strong> — Calendar (for appointment booking) and Business Profile (for optional setup auto-fill), only when you explicitly connect them.</li>
                <li><strong>Stripe</strong> — payment processing and billing.</li>
                <li><strong>Supabase</strong> — our database and account authentication.</li>
                <li><strong>Resend</strong> — transactional email delivery.</li>
              </ul>
            </Section>

            <Section title="5. Call recording">
              <p>
                Calls to an Oviflow-powered number may be recorded and transcribed to provide the
                service and generate summaries for the business owner. Business owners are
                responsible for ensuring their use of call recording complies with applicable
                law in their jurisdiction, including any requirement to notify callers that a
                call may be recorded.
              </p>
            </Section>

            <Section title="6. Data retention">
              <p>
                We retain call recordings, transcripts, and account data for as long as your
                account is active, or as needed to provide the service and meet legal
                obligations. You can request deletion of your account and associated data at any
                time by contacting us.
              </p>
            </Section>

            <Section title="7. Your rights">
              <p>
                Depending on your location, you may have rights to access, correct, or delete
                your personal information, or to object to certain uses of it. To exercise any of
                these rights, contact us using the details below.
              </p>
            </Section>

            <Section title="8. Security">
              <p>
                We use industry-standard measures to protect your data, including encryption in
                transit and restricted access to production systems. No method of transmission
                or storage is 100% secure, and we cannot guarantee absolute security.
              </p>
            </Section>

            <Section title="9. Changes to this policy">
              <p>
                We may update this policy from time to time. We&apos;ll update the &quot;Last
                updated&quot; date above when we do. Continued use of Oviflow after a change means
                you accept the updated policy.
              </p>
            </Section>

            <Section title="10. Contact us">
              <p>
                Questions about this policy or your data? Email us at{" "}
                <a href="mailto:privacy@oviflow.io" className="text-violet-600 hover:underline">
                  privacy@oviflow.io
                </a>
                .
              </p>
            </Section>
          </div>
        </div>

        <Link
          href="/"
          className="mt-6 inline-block text-sm text-neutral-500 hover:text-violet-600 transition-colors"
        >
          ← Back to home
        </Link>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="text-base font-semibold text-neutral-900 mb-2">{title}</h2>
      {children}
    </div>
  );
}
